site_name: CloudCon 2025
theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/logo.png
  palette:
    primary: white
    # accent: deep orange
  features:
    - navigation.tabs
    - navigation.tabs.sticky
# plugins:
#   - social
plugins: []
site_url: https://cloudcon.au
nav:
  - Home: "/"
  - Speakers & Call for Papers: "speakers.md"
  - Sponsors: "sponsors.md"
  - Agenda: "agenda.md"
  - Register / Attend: "register.md"

  
extra:
  social:
      - icon: fontawesome/brands/linkedin 
        link: https://www.linkedin.com/company/cloudnativesydney
extra_css:
  - overrides/assets/stylesheets/extra.css
markdown_extensions: 
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
